//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoboViajaNet.ConexaoBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class DadosPagamento
    {
        public int DadosPagamentoId { get; set; }
        public string NumeroCartao { get; set; }
        public string Cvv { get; set; }
        public string NomeImpressoNoCartao { get; set; }
        public System.DateTime Validade { get; set; }
        public System.DateTime DataCadastro { get; set; }
        public int ClienteId { get; set; }
    
        public virtual Cliente Cliente { get; set; }
    }
}
