//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoboViajaNet.ConexaoBD
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TesteViajaNetEntities : DbContext
    {
        public TesteViajaNetEntities()
            : base("name=TesteViajaNetEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cliente> Cliente { get; set; }
        public virtual DbSet<DadosNavegacao> DadosNavegacao { get; set; }
        public virtual DbSet<DadosPagamento> DadosPagamento { get; set; }
        public virtual DbSet<Endereco> Endereco { get; set; }
        public virtual DbSet<Landing> Landing { get; set; }
    }
}
